spring:
  data:
    mongodb:
      database: icode

file:
  name: index.html

execution:
  result:
    endpoint:
      http://localhost:8080/api/v1/execution-result/

jwt:
  signing:
    key: bUfsYV8UrwDjVUjGmIuxd4vNT2AKlcph
  issuer: icode-app

error:
  trace:
    enabled: true
    disabledMessage: Trance is not enabled. Enable it to fill this property!

notification-service:
  baseURL: http://localhost:8081