spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: icode-service
      password: icode-service-dev
      database: data
      authentication-database: admin

notification-service:
  baseURL: http://localhost:8081